<?php
// created: 2018-04-27 09:22:48
$dictionary["te_MapitemtoDispatch"]["fields"]["semester"] = array (
	  'inline_edit' => '1',
      'labelValue' => 'Semester',
      'required' => true,
      'source' => 'non-db',
      'name' => 'semester',
      'vname' => 'Semester',
      'type' => 'relate',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'te_te_semester_id',
      'ext2' => 'te_te_semester',
      'module' => 'te_te_semester',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
      'id' => 'te_MapitemtoDispatchsemester',
      #'custom_module' => 'te_dispatch_request_item',
);
$dictionary["te_MapitemtoDispatch"]["fields"]["te_te_semester_id"] = array (
	  'inline_edit' => 1,
      'required' => false,
      'name' => 'te_te_semester_id',
      'vname' => 'LBL_SEMESTER_TE_TE_SEMESTER_ID',
      'type' => 'id',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '36',
      'size' => '20',
      'id' => 'te_MapitemtoDispatch_te_semester_id',
      #'custom_module' => 'te_dispatch_request_item',
);
?>
