 <?php 
 /* Auto genrated Field Suitecrm create By manish Gupta*/
$dictionary["te_student_batch"]["fields"]["admission_type"] = array (
	  'required' => false,
      'name' => 'admission_type',
      'vname' => 'Admission Type',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'admission_list_type',
      'studio' => 'visible',
      'dependency' => false,
    );
 /* Auto genrated Field Suitecrm create By manish Gupta*/
$dictionary["te_student_batch"]["fields"]["specialization"] = array (
	  'required' => false,
      'name' => 'specialization',
      'vname' => 'Specialization',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'specialization_list',
      'studio' => 'visible',
      'dependency' => false,
    );
    /* Auto genrated Field Suitecrm create By manish Gupta*/
$dictionary["te_student_batch"]["fields"]["promotional_kit"] = array (
	  'required' => false,
      'name' => 'promotional_kit',
      'vname' => 'Promotional Kit',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'promotional_kit_list',
      'studio' => 'visible',
      'dependency' => false,
    );
    /* Auto genrated Field Suitecrm create By manish Gupta*/
 $dictionary["te_student_batch"]["fields"]["date_of_enrolment"] = array (
	  'required' => false,
      'name' => 'date_of_enrolment',
      'vname' => 'Date of Enrolment',
      'type' => 'date',
      'massupdate' => false,
      'comments' => '',
      'help' => 'date on which the converted lead is enrolled by University',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'studio' => 'visible',
    );
   /* Auto genrated Field Suitecrm create By manish Gupta*/ 
 $dictionary["te_student_batch"]["fields"]["to_be_enrolled_date"] = array (
	  'required' => false,
      'name' => 'to_be_enrolled_date',
      'vname' => 'To Be Enrolled Date',
      'type' => 'date',
      'massupdate' => false,
      'comments' => 'date on which sales team has converted this lead',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'studio' => 'visible',
    );  
    /* Auto genrated Field Suitecrm create By manish Gupta*/
 $dictionary["te_student_batch"]["fields"]["course_expiry_date"] = array (
	  'required' => false,
      'name' => 'course_expiry_date',
      'vname' => 'Course Expiry Date',
      'type' => 'date',
      'massupdate' => false,
      'comments' => 'date on which the course will expire',
      'help' => 'Date on which the course will expire',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'studio' => 'visible',
    );  
    
