<?php
$dictionary['te_ba_Batch']['fields']['discount_in_inr'] = array (
      'required' => false,
      'name' => 'discount_in_inr',
      'vname' => 'Discount In INR',
      'type' => 'float',
      'massupdate' => 0,
      'no_default' => false,
      'studio' => 'visible',
      'comments' => '',
      'help' => 'Discount field',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',    
   );
   
   
$dictionary['te_ba_Batch']['fields']['discount_in_usd'] = array (
      'required' => false,
      'name' => 'discount_in_usd',
      'vname' => 'Discount In USD',
      'type' => 'float',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'studio' => 'visible',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',  
   );
   ?>
