 <?php 
$dictionary["te_student_batch"]["fields"]["current_sems"] = array (
	  'required' => false,
      'name' => 'current_sems',
      'vname' => 'Current Sem',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'function' => 'sem_List',
      'studio' => 'visible',
      'dependency' => false,
    );
  <?php
