<p>
	Twitter Feed plugin for WordPress allows you to easily display Twitter user timelines in a wide variety of ways, using the included shortcode engine and widget. 
	The included skins are fully responsive. The plugin has the option of caching tweets to improve the performance of the plugin.
	Visit the official <a href="http://products.askupasoftware.com/twitter-feed/">Twitter Feed</a> page for live examples, code snippets and more information.
</p>
<p>
	Follow us on <a href="http://twitter.com/askupasoftware">Twitter</a> and on <a href="http://facebook.com/askupasoftware">Facebook</a> to get the latest updates and version releases.
</p>
<p><strong>Feature List:</strong></p>
<ul class="askupa-list">
	<li>Twitter API 1.1</li>
	<li>Shortcodes + shortcode editor</li>
	<li>Widget</li>
	<li>LTR and RTL support</li>
	<li>Powerful Caching system</li>
	<li>Tweet customization</li>
	<li>Tweet actions</li>
	<li>100% responsive</li>
	<li>Illustrated step-by-step guide</li>
	<li>Clean & simple plugin options page</li>
	<li>Very simple to setup</li>
</ul>
<h2>About Askupa Software</h2>
<p>
	Askupa Software specializes in web design and development for the widely used WordPress CMS. We are passionate about what we do, and our products show it.
        All of our WordPress themes/plugins are developed on a solid foundation - Amarkal. Currently in its alpha stages, Amarkal is an open-source PHP development framework with a fully-stacked WordPress extension.
        Our testing process verifies that each of our products is compatible with all modern browsers and devices. Our build process automatically adds all the code necessary for backward compatibility.
	Our unique design process guarantees the high quality of the software product in terms of robustness, scalability, completeness and maintainability.
</p>