 <?php 
$dictionary["te_pr_Programs"]["fields"][" m_c_qualifecation"] = array (
	  'required' => false,
      'name' => 'm_c_qualifecation',
      'vname' => 'Master Course Qualification',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'mcq_list',
      'studio' => 'visible',
      'dependency' => false,
    );
  ?>
  <?php 
$dictionary["te_pr_Programs"]["fields"]["filter_stream_name"] = array (
	  'required' => false,
      'name' => 'filter_stream_name',
      'vname' => 'Filter Stream Name',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'fsn_list',
      'studio' => 'visible',
      'dependency' => false,
    ); 
    ?>
   <?php 
$dictionary["te_pr_Programs"]["fields"]["duration"] = array (
	  'required' => false,
      'name' => 'duration',
      'vname' => 'Duration',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'duration_list',
      'studio' => 'visible',
      'dependency' => false,
    );
 ?>
 <?php
$dictionary["te_pr_Programs"]["fields"]["payment_gateway"] = array (
	  'required' => false,
      'name' => 'payment_gateway',
      'vname' => 'Payment Gateway',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'payment_gateway_list',
      'studio' => 'visible',
      'dependency' => false,
    );
   ?> 
   <?php 
$dictionary["te_pr_Programs"]["fields"]["learning_m_s "] = array (
	  'required' => false,
      'name' => 'learning_m_s',
      'vname' => 'Learning Management System',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'learning_m_s_list',
      'studio' => 'visible',
      'dependency' => false,
    );

    ?>
