<?php
$dictionary["te_srm_auto_assignment"]["fields"]["status"] = array (
	  'required' => false,
      'name' => 'status',
      'label' => 'LBL_STATUS',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'srmauto_status_list',
      'studio' => 'visible',
      'dependency' => false,
    );
 ?>
