<?php
/* Pin Code Number Enter @ Manish gupta Date 30 March 2018*/

$dictionary['te_in_institutes']['fields']['Pincode'] =array (
		'name' => 'Pincode',
		'vname' => 'Pincode',
		'type' => 'int',
		'required' => false,
		'comments' => 'pin code ',
		'help' => '',
		'default'=> '',
		'importable' => 'false',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => false,
		'len' => '50',
		'size' => '50',
	);
	/* fax number */
$dictionary['te_in_institutes']['fields']['faxnumber'] =array (
		'name' => 'faxnumber',
		'vname' => 'Fax Number',
		'type' => 'phone',
		'required' => false,
		'comments' => 'fax number ',
		'help' => '',
		'default'=> '',
		'importable' => 'false',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => false,
		'dbType' => 'varchar',
		'len' => '255',
		'size' => '10',
	);
	/* Short Name, */
$dictionary['te_in_institutes']['fields']['short_name'] =array (
		'name' => 'short_name',
		'vname' => 'Short Name',
		'type' => 'varchar',
		'required' => false,
		'comments' => 'Institute Short name enter here ',
		'help' => '',
		'default'=> '',
		'importable' => 'false',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => false,
		'len' => '100',
		'size' => '50',
	);
	/*  Institute Short Code */
$dictionary['te_in_institutes']['fields']['institute_code'] =array (
		'name' => 'institute_code',
		'vname' => 'Institute(Source)Code',
		'type' => 'varchar',
		'required' => true,
		'comments' => 'Institute Short name enter here ',
		'help' => '',
		'default'=> '',
		'importable' => 'false',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => false,
		'len' => '255',
		'size' => '30',
	);
	/*  Email Adress Field */ 
	$dictionary['te_in_institutes']['fields']['email'] =array (
        'name' => 'email',
        'label' => 'Email',
        'type' => 'varchar',
        'help' => '',
        'comment' => '',
        'default_value' => '',
        'len' => '255',
		'size' => '20',
        'required' => false,
        'reportable' => true,
        'audited' => false,
        'importable' => 'true',
        'duplicate_merge' => false,
);
/* Addresss line 1 Adreesss Line 2 */
$dictionary['te_in_institutes']['fields']['address_line1'] =array (
			'name' => 'address_line1',
            'label' => 'Address Line 1',
            'type' => 'varchar',
            'help' => 'Address Line 1',
            'comment' => 'Address line 1',
            'default_value' => '',
            'max_size' => 255,
            'required' => false,
            'reportable' => true,
            'audited' => false,
            'importable' => 'true',
            'duplicate_merge' => false,
);
$dictionary['te_in_institutes']['fields']['address_line2'] =array (
			'name' => 'address_line2',
            'label' => 'Address Line 2',
            'type' => 'varchar',
            'help' => 'Addresss line2',
            'comment' => 'Address Line2',
            'default_value' => '',
            'max_size' => 255,
            'required' => false,
            'reportable' => true,
            'audited' => false,
            'importable' => 'true',
            'duplicate_merge' => false,
);
/* institute url Field  */
$dictionary['te_in_institutes']['fields']['institute_url'] =array (
			'name' => 'institute_url',
            'label' => 'Institute URL',
            'type' => 'varchar',
            'help' => 'institute url',
            'comment' => 'Full institute url',
            'default_value' => '',
            'max_size' => 255,
            'required' => false,
            'reportable' => true,
            'audited' => false,
            'importable' => 'true',
            'duplicate_merge' => false,
);
/* Challan Line 1,Challan Line 2,Challan Line 3,*/
$dictionary['te_in_institutes']['fields']['Challan_line1'] =array (
		'name' => 'Challan_line1',
		'vname' => 'Challan Line 1',
		'type' => 'varchar',
		'required' => false,
		'comments' => 'Institute Short name enter here ',
		'help' => '',
		'default'=> '',
		'importable' => 'false',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => false,
		'len' => '255',
		'size' => '20',
	);
	$dictionary['te_in_institutes']['fields']['Challan_line2'] =array (
		'name' => 'Challan_line2',
		'vname' => 'Challan Line 2',
		'type' => 'varchar',
		'required' => false,
		'comments' => 'Challan_line2',
		'help' => '',
		'default'=> '',
		'importable' => 'false',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => false,
		'len' => '255',
		'size' => '20',
	);
	$dictionary['te_in_institutes']['fields']['Challan_line3'] =array (
		'name' => 'Challan_line3',
		'vname' => 'Challan Line 3',
		'type' => 'varchar',
		'required' => false,
		'comments' => 'Challan_line 3 ',
		'help' => '',
		'default'=> '',
		'importable' => 'false',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => false,
		'len' => '255',
		'size' => '20',
	);
	$dictionary['te_in_institutes']['fields']['marksheet_no'] =array (
		'name' => 'marksheet_no',
		'vname' => 'Marksheet No.',
		'type' => 'varchar',
		'required' => false,
		'comments' => 'marksheet_no ',
		'help' => '',
		'default'=> '',
		'importable' => 'false',
		'duplicate_merge' => 'disabled',
		'duplicate_merge_dom_value' => '0',
		'audited' => false,
		'reportable' => false,
		'len' => '100',
		'size' => '50',
	);
<?php

