<div class="content-wrapper" style="min-height: 916px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
       <?php echo $head_title; ?>
      </h1>
      <ol class="breadcrumb">
        <li><a href="<?php echo base_url('dashboard');?>"><i class="fa fa-dashboard"></i> Home</a></li>
        <li>Plans</li>
        <li class="active"><?php echo $head_title; ?></li>
      </ol>
    </section>
	<input type="hidden" class="delete_url" value="<?php echo base_url('plans/hide'); ?>" />
    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">All Tracking numbers generated by Software</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
				  <th>Account linked</th>
				  <th>Title</th>
                  <th>Tracking number</th>
				    <th>Created date</th>
                   <th style="width:220px;">Action</th>
                </tr>
                </thead>
                <tbody>
				<?php
 
		if(!empty($total_ups))
		{
					foreach($total_ups as $data)
					{ 
					
					?>
					<tr id="row_<?php echo $data->id; ?>">
					 
					  <td style="word-break: break-word;"><img src="../assets/images/<?php echo $data->account_type; ?>.jpg"  width="40px"></td>
					  
					  <td style="word-break: break-word;"><?php echo $data->user_account_name; ?></td>
					   <td style="word-break: break-word;"><?php echo $data->tracking_number; ?></td>
					   <td style="word-break: break-word;"><?php echo $data->create_date; ?></td>
						<td style="word-break: break-word;"><a class="btn btn-app" href="<?php echo base_url('plans/plan/'.$data->id); ?>"><i class="fa fa-eye"></i> View</a>
						<a class="btn btn-app" href="<?php echo base_url('plans/edit_plan/'.$data->id); ?>"><i class="fa fa-edit"></i> Edit</a>
						<a class="btn btn-app delete-alert" data-id="<?php echo $data->id; ?>" href="#" ><i class="fa fa-trash"></i> Delete</a>
					  </td>
					</tr>
					<?php }
				}?>
				
				
                </tbody>
                <tfoot>
                <tr>
               
				 <th>Account linked</th>
				  <th>Title</th>
                  <th>Tracking number</th>
				    <th>Created date</th>
                   <th style="width:220px;">Action</th>
                </tr>
                </tfoot>
              </table>
			 
            </div>
            <!-- /.box-body --> 
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
	
				
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
  <style>
   .account_label_tag1
  {
      display: flex;
  }
  .account_label_tag
  {
	  margin:50px;
	  width:300px; 
  }
  .account_label
  {
	  text-align:center;
	  background: #F6F6f6;
	  color:fff;
	padding:15px;
	  font-size:15px;
	  width:300px;
  }
  .card {
    box-shadow: rgba(0, 0, 0, 0.05) 0px 1px 2px, rgba(63, 63, 68, 0.1) 0px 0px 0px 1px;
    background-color: rgb(255, 255, 255);
    margin-bottom: 30px;
    border-radius: 4px;
	width:300px
}
.card-user img {
    height: 150px;
	width:300px;
}
<style>…</style>
.card .image {
   
    position: relative;
    transform-style: preserve-3d;
    overflow: hidden;
    border-radius: 4px 4px 0px 0px;
}
.author,
 .content_main {
   
	 padding: 31px ;
}


.card-user .author {
    text-align: center;
    text-transform: none;
    margin-top: 0px;
}

.card .author {
    font-size: 12px;
    font-weight: 600;
    text-transform: uppercase;
    word-wrap: break-word;
}
  </style>